### ISSUE TITLE
Optimize UI for small screens

### ISSUE THREAD

**Issue by JuliusHenke** [TorMap/tormap#1]
- [x] All settings are usable
- [x] Stats can be displayed when needed
- [x] Dialogs can be properly viewed
- [x] Update to MUI v5: https://mui.com/blog/mui-core-v5/

**Comment by TimKilb** [comment]
Opend Issue #20 for simpler component parameters.

I suggest 2 diffrent controle Components whitch are drawn for either wide or small screens
- [ ] Move current Controles into a Controles component for wide screens.
- [ ] Create new controles component for small screens.

**Comment by TimKilb** [comment]
Opend Issue #20 for simpler component parameters.

I suggest 2 diffrent controle Components whitch are drawn for either wide or small screens
- [ ] Move current Controles into a Controles component for wide screens.
- [ ] Create new controles component for small screens.

**Comment by TimKilb** [comment]
Optimize dialogs for small and big screensizes

- [ ] screens over 600px width
- [ ] screens under 600px
